### ISSUE TITLE
wish: Add "Differences from vex" or "Upgrading from vex" section

### ISSUE THREAD

**Issue by markstos** [bbatliner/vex2#2]
For vex users, it would be useful to have a section in the documentation to clarify what changes they need to make to switch, and any  incompatible API changes that have been made.

**Comment by bbatliner** [comment]
I moved most of `vex2` back into my fork of `vex`, and starting prepping there for a [PR back into vex](https://github.com/HubSpot/vex/pull/160). I wrote [UPGRADING.md](https://github.com/bbatliner/vex/blob/master/UPGRADING.md) to address your concern. Is it clear enough? Did you find any other breaking changes that I didn't document?

**Comment by markstos** [comment]
The Upgrading guide looks great to me. It's missing a section on the breaking safe-by-default changes to vex-dialog. If that's going to be documented in vex-dialog, it could be linked to there, but the overview of the breaking changes would still be good mention in this upgrading doc.

**Comment by bbatliner** [comment]
True - I'm not sure yet where that documentation will end up, but it is missing presently. I will go back to your safe dialog fork and merge some documentation over.
